### PR TITLE
Expire token if it already exists then set new one

### PR DESCRIPTION
**Pull request by Jeketam**
For issue #2

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Hi @Jeketam,
Thanks for your contribution. A few points:
- When setting the expiry time to be `0`, will the cookie be completely removed from the response or will it still be there with an expiry time of 0? For example, if the cookie has `abc=val`, and I set `abc=val1`, then the output of `Set-cookie: abc=val, expiry=Thu, Jan 1 1970; abc=val1, expiry=<some time in the future>` may lead to an undefined behaviour where the browser may end up first setting `val1`, and then overwriting it with `val` (which will also remove it due to the expiry). What we would ideally prefer is to completely remove `val` from the cookie so that the final output is `Set-cookie: abc=val1, expiry=<some time in the future>`.

- If you could also contribute some tests for this, that would be great. Examples of tests can be found here: https://github.com/supertokens/supertokens-flask/issues/2#issue-702240731

**Comment by jscyo** [comment]
@Jeketam Hey, are you still working on this?

**Comment by Jeketam** [comment]
@jscyo I have tests written but I'm having trouble getting the testing environment from supertokens-core running on my machine

**Comment by rishabhpoddar** [comment]
Hey @Jeketam. You can push your tests, and I'll test it for you :)

**Pull request closed without merging**
